### ISSUE TITLE
Test regression with zlib 1.2.12

### ISSUE THREAD

**Issue by mweinelt** [pmqs/Compress-Raw-Zlib#7] opened 2022-04-02 01:18 UTC
Since upgrading zlib to 1.2.12 we see the following regression in this package with version 2.101. I'm not sure what these mean.

```
t/000prereq.t ...... # Running Perl version  5.034000
t/000prereq.t ...... ok   
t/01version.t ...... ok   
t/02zlib.t ......... 1/349 
#     Failed test (t/02zlib.t at line 493)
#          got: 1
#     expected: -3

#     Failed test (t/02zlib.t at line 517)
#          got: 1
#     expected: -3
# Looks like you failed 2 tests of 349.
t/02zlib.t ......... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/349 subtests 
t/07bufsize.t ...... skipped: Lengthy Tests Disabled
t/09limitoutput.t .. ok       
t/18lvalue.t ....... ok     
t/19nonpv.t ........ ok     
t/99pod.t .......... skipped: Test::Pod 1.00 required for testing POD
t/meta-json.t ...... skipped: Test::CPAN::Meta::JSON required for testing META.json
t/meta-yaml.t ...... skipped: Test::CPAN::Meta required for testing META.yml

Test Summary Report
-------------------
t/02zlib.t       (Wstat: 512 Tests: 349 Failed: 2)
  Failed tests:  126, 134
  Non-zero exit status: 2
Files=10, Tests=507,  1 wallclock secs ( 0.10 usr  0.02 sys +  0.85 cusr  0.10 csys =  1.07 CPU)
Result: FAIL
Failed 1/10 test programs. 2/507 subtests failed.
make: *** [Makefile:1053: test_dynamic] Error 255
```

**Comment by vcunat** [comment] 2022-04-02 07:13
Decoding the `#define`s, these are two cases of `Z_STREAM_END` instead of `Z_DATA_ERROR` when calling `inflate()`.

**Comment by pmqs** [comment] 2022-04-02 07:31
Thanks guys - already know about this one. Fix is in the works. 

This is a duplicate of https://github.com/pmqs/Compress-Raw-Zlib/issues/6, so closing this ticket.

**Comment by vcunat** [comment] 2022-04-02 07:36
I read that one before posting, but it did not seem like this "test problem" was known.   A quick question &ndash; the fix won't be just in the tests, right?

**Comment by pmqs** [comment] 2022-04-02 07:41
The main part of the fix is to include the new zlib 1.2.12 source in the module. Apart from that, it is dealing with this test failure. Haven't had the time to see if the test failure is my problem or if it is a regression in zlib itself.

**Closed** 2022-04-02 07:43 UTC
Labels: duplicate

**Comment by vcunat** [comment] 2022-04-02 07:46
Yeah, well in distro we use `BUILD_ZLIB   = False` so the first part doesn't seem interesting for us :-)

**Comment by wamserma** [comment] 2022-04-02 20:02
Thanks to the power of Nix I did a quick bisect and it seems the issue was introduced with https://github.com/madler/zlib/commit/0d36ec47f310478549c0864f215ab5c0114c49ba - building against the previous commit (https://github.com/madler/zlib/commit/7c0c75e990ca5395139c148f120042048b0ce091) worked fine.
To reproduce, check out https://github.com/NixOS/nixpkgs/commit/1dd6e44b72843db4b10afeb91d9f35188dab378b, apply this patch
```
diff --git a/pkgs/top-level/perl-packages.nix b/pkgs/top-level/perl-packages.nix
index 3435eeee25e..da217d2ab2b 100644
--- a/pkgs/top-level/perl-packages.nix
+++ b/pkgs/top-level/perl-packages.nix
@@ -15,6 +15,30 @@
 # cpan2nix assumes that perl-packages.nix will be used only with perl 5.30.3 or above
 assert lib.versionAtLeast perl.version "5.30.3";
 let
+
+  myzlib_bad = pkgs.zlib.overrideAttrs (old: {
+      version = "2.2.11-git";
+      src = fetchFromGitHub {
+       owner = "madler";
+       repo = "zlib";
+       rev = "0d36ec47f310478549c0864f215ab5c0114c49ba";
+       sha256 = "113n8d6fcyqxaxs255pgqdcyk3rjwa9i8b76kh4a0hsa7fcxxx3p";
+    };
+  });
+
+  myzlib_good = pkgs.zlib.overrideAttrs (old: {
+      version = "2.2.11-git";
+      src = fetchFromGitHub {
+       owner = "madler";
+       repo = "zlib";
+       rev = "7c0c75e990ca5395139c148f120042048b0ce091";
+       sha256 = "0gxzb6ghd0qlbja83fasbm2dsa3a89w0ba9xfp34ym3w5cs1hirm";
+    };
+  });
+
+  myzlib = myzlib_bad;
+
+
   inherit (lib) maintainers teams;
   self = _self // (overrides pkgs);
   _self = with self; {
@@ -3559,8 +3583,8 @@ let
     preConfigure = ''
       cat > config.in <<EOF
         BUILD_ZLIB   = False
-        INCLUDE      = ${pkgs.zlib.dev}/include
-        LIB          = ${pkgs.zlib.out}/lib
+        INCLUDE      = ${myzlib.dev}/include
+        LIB          = ${myzlib.out}/lib
         OLD_ZLIB     = False
         GZIP_OS_CODE = AUTO_DETECT
       EOF

```
and do a `nix-build . -A perlPackages.CompressZlib` from the root folder of this checkout.

**Comment by vcunat** [comment] 2022-04-02 20:05
I didn't look deeply into what the failing tests do, but it seemed like the case of
> allows a successful return if the compressed data terminated in a graceful manner

**Comment by pmqs** [comment] 2022-04-03 16:58
> Thanks to the power of Nix I did a quick bisect and it seems the issue was introduced with [madler/zlib@0d36ec4](https://github.com/madler/zlib/commit/0d36ec47f310478549c0864f215ab5c0114c49ba) - building against the previous commit ([madler/zlib@7c0c75e](https://github.com/madler/zlib/commit/7c0c75e990ca5395139c148f120042048b0ce091)) worked fine. To reproduce, check out [NixOS/nixpkgs@1dd6e44](https://github.com/NixOS/nixpkgs/commit/1dd6e44b72843db4b10afeb91d9f35188dab378b), apply this patch
> 
> ```
> diff --git a/pkgs/top-level/perl-packages.nix b/pkgs/top-level/perl-packages.nix
> index 3435eeee25e..da217d2ab2b 100644
> --- a/pkgs/top-level/perl-packages.nix
> +++ b/pkgs/top-level/perl-packages.nix
> @@ -15,6 +15,30 @@
>  # cpan2nix assumes that perl-packages.nix will be used only with perl 5.30.3 or above
>  assert lib.versionAtLeast perl.version "5.30.3";
>  let
> +
> +  myzlib_bad = pkgs.zlib.overrideAttrs (old: {
> +      version = "2.2.11-git";
> +      src = fetchFromGitHub {
> +       owner = "madler";
> +       repo = "zlib";
> +       rev = "0d36ec47f310478549c0864f215ab5c0114c49ba";
> +       sha256 = "113n8d6fcyqxaxs255pgqdcyk3rjwa9i8b76kh4a0hsa7fcxxx3p";
> +    };
> +  });
> +
> +  myzlib_good = pkgs.zlib.overrideAttrs (old: {
> +      version = "2.2.11-git";
> +      src = fetchFromGitHub {
> +       owner = "madler";
> +       repo = "zlib";
> +       rev = "7c0c75e990ca5395139c148f120042048b0ce091";
> +       sha256 = "0gxzb6ghd0qlbja83fasbm2dsa3a89w0ba9xfp34ym3w5cs1hirm";
> +    };
> +  });
> +
> +  myzlib = myzlib_bad;
> +
> +
>    inherit (lib) maintainers teams;
>    self = _self // (overrides pkgs);
>    _self = with self; {
> @@ -3559,8 +3583,8 @@ let
>      preConfigure = ''
>        cat > config.in <<EOF
>          BUILD_ZLIB   = False
> -        INCLUDE      = ${pkgs.zlib.dev}/include
> -        LIB          = ${pkgs.zlib.out}/lib
> +        INCLUDE      = ${myzlib.dev}/include
> +        LIB          = ${myzlib.out}/lib
>          OLD_ZLIB     = False
>          GZIP_OS_CODE = AUTO_DETECT
>        EOF
> ```
> 
> and do a `nix-build . -A perlPackages.CompressZlib` from the root folder of this checkout.

Thanks for doing the bisect - makes it a it easier for me to have confidence in the fix I'm applying for this issue.

**Comment by pmqs** [comment] 2022-04-03 20:06
Fix uploaded to github & to CPAN
